function buildDate(offsetDays) {
  const date = new Date();
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString().slice(0, 10);
}

function buildTimestamp(offsetDays) {
  const date = new Date();
  date.setDate(date.getDate() - offsetDays);
  return date.toISOString();
}

export function buildDemoOpportunities(elders = [], organizationId = "") {
  if (!elders.length) return [];

  const [elderA, elderB = elderA, elderC = elderB] = elders;

  return [
    {
      id: `demo-op-ai-1-${elderA.id}`,
      organizationId,
      elderId: elderA.id,
      type: "重点关注",
      title: "建议安排一次温和回访",
      description: `根据最近服务记录，建议本周对${elderA.name}安排一次温和回访，可从熟悉话题切入。`,
      status: "pending",
      source: "ai",
      dueDate: buildDate(1),
      createdAt: buildTimestamp(0),
      updatedAt: buildTimestamp(0),
    },
    {
      id: `demo-op-ai-2-${elderB.id}`,
      organizationId,
      elderId: elderB.id,
      type: "重点关注",
      title: "建议补充一次近况了解",
      description: `建议联系${elderB.name}家属补充近期生活变化，为下次服务准备更多背景信息。`,
      status: "pending",
      source: "ai",
      dueDate: buildDate(2),
      createdAt: buildTimestamp(1),
      updatedAt: buildTimestamp(1),
    },
    {
      id: `demo-op-ai-3-${elderC.id}`,
      organizationId,
      elderId: elderC.id,
      type: "重点关注",
      title: "建议安排一次短时问候",
      description: `AI建议先用电话或短探访方式关心${elderC.name}的近期心情和睡眠情况。`,
      status: "pending",
      source: "ai",
      dueDate: buildDate(3),
      createdAt: buildTimestamp(2),
      updatedAt: buildTimestamp(2),
    },
    {
      id: `demo-op-ai-4-${elderA.id}`,
      organizationId,
      elderId: elderA.id,
      type: "活动邀请",
      title: "建议安排一次轻活动陪伴",
      description: `如果${elderA.name}愿意参与轻活动，可边做边聊，帮助观察近期状态。`,
      status: "pending",
      source: "ai",
      dueDate: buildDate(4),
      createdAt: buildTimestamp(3),
      updatedAt: buildTimestamp(3),
    },
    {
      id: `demo-op-ai-5-${elderB.id}`,
      organizationId,
      elderId: elderB.id,
      type: "电话问候",
      title: "建议延续上次熟悉话题",
      description: `AI建议下次继续从${elderB.name}熟悉的话题进入，减少陌生提问压力。`,
      status: "pending",
      source: "ai",
      dueDate: buildDate(5),
      createdAt: buildTimestamp(4),
      updatedAt: buildTimestamp(4),
    },
    {
      id: `demo-op-rule-1-${elderA.id}`,
      organizationId,
      elderId: elderA.id,
      type: "长期未探访",
      title: "超过 7 天未形成服务记录",
      description: `${elderA.name}已有一段时间没有新的服务记录，建议安排一次电话问候或现场探访。`,
      status: "pending",
      source: "rule",
      dueDate: buildDate(1),
      createdAt: buildTimestamp(0),
      updatedAt: buildTimestamp(0),
    },
    {
      id: `demo-op-rule-2-${elderB.id}`,
      organizationId,
      elderId: elderB.id,
      type: "生日关怀",
      title: "生日关怀提醒",
      description: `${elderB.name}的关怀日期临近，建议提前准备一句祝福或邀请家属录制语音问候。`,
      status: "pending",
      source: "rule",
      dueDate: buildDate(6),
      createdAt: buildTimestamp(1),
      updatedAt: buildTimestamp(1),
    },
    {
      id: `demo-op-rule-3-${elderC.id}`,
      organizationId,
      elderId: elderC.id,
      type: "画像待完善",
      title: "知老卡信息待完善",
      description: `${elderC.name}的部分知老卡字段仍较少，建议下次服务后补充家属提醒或沟通禁忌。`,
      status: "pending",
      source: "rule",
      dueDate: buildDate(7),
      createdAt: buildTimestamp(2),
      updatedAt: buildTimestamp(2),
    },
    {
      id: `demo-op-rule-4-${elderA.id}`,
      organizationId,
      elderId: elderA.id,
      type: "电话问候",
      title: "本周应补一次近况回访",
      description: `根据固定规则，本周建议完成一次对${elderA.name}的近况回访。`,
      status: "pending",
      source: "rule",
      dueDate: buildDate(8),
      createdAt: buildTimestamp(3),
      updatedAt: buildTimestamp(3),
    },
    {
      id: `demo-op-rule-5-${elderB.id}`,
      organizationId,
      elderId: elderB.id,
      type: "画像待完善",
      title: "建议补充家属提醒信息",
      description: `系统发现${elderB.name}的家属协同信息较少，建议下次服务后补充。`,
      status: "pending",
      source: "rule",
      dueDate: buildDate(9),
      createdAt: buildTimestamp(4),
      updatedAt: buildTimestamp(4),
    },
    {
      id: `demo-op-manual-1-${elderC.id}`,
      organizationId,
      elderId: elderC.id,
      type: "探访安排",
      title: "本周五安排一次入户探访",
      description: `工作人员手动创建：本周五下午安排志愿者探访${elderC.name}，重点了解近期生活状态。`,
      status: "pending",
      source: "manual",
      createdByName: "王老师",
      createdByRole: "staff",
      dueDate: buildDate(2),
      createdAt: buildTimestamp(0),
      updatedAt: buildTimestamp(0),
    },
    {
      id: `demo-op-manual-2-${elderA.id}`,
      organizationId,
      elderId: elderA.id,
      type: "电话问候",
      title: "联系家属补充近况",
      description: `工作人员手动创建：请联系家属了解${elderA.name}最近饮食、睡眠和情绪情况。`,
      status: "pending",
      source: "manual",
      createdByName: "刘社工",
      createdByRole: "staff",
      dueDate: buildDate(3),
      createdAt: buildTimestamp(1),
      updatedAt: buildTimestamp(1),
    },
    {
      id: `demo-op-manual-3-${elderB.id}`,
      organizationId,
      elderId: elderB.id,
      type: "活动邀请",
      title: "邀请参加周末茶话会",
      description: `工作人员手动创建：如果${elderB.name}状态合适，可邀请参加周末社区茶话会。`,
      status: "pending",
      source: "manual",
      createdByName: "机构管理员",
      createdByRole: "org_admin",
      dueDate: buildDate(4),
      createdAt: buildTimestamp(2),
      updatedAt: buildTimestamp(2),
    },
    {
      id: `demo-op-manual-4-${elderC.id}`,
      organizationId,
      elderId: elderC.id,
      type: "电话问候",
      title: "周三上午安排一次电话关怀",
      description: `工作人员手动创建：周三上午电话问候${elderC.name}，重点了解本周精神和睡眠状态。`,
      status: "pending",
      source: "manual",
      createdByName: "王老师",
      createdByRole: "staff",
      dueDate: buildDate(5),
      createdAt: buildTimestamp(3),
      updatedAt: buildTimestamp(3),
    },
    {
      id: `demo-op-manual-5-${elderA.id}`,
      organizationId,
      elderId: elderA.id,
      type: "电话问候",
      title: "联系家属确认本周安排",
      description: `工作人员手动创建：请与${elderA.name}家属确认本周探访或语音祝福安排。`,
      status: "pending",
      source: "manual",
      createdByName: "刘社工",
      createdByRole: "staff",
      dueDate: buildDate(6),
      createdAt: buildTimestamp(4),
      updatedAt: buildTimestamp(4),
    },
  ];
}
