import { getChineseElderAvatar } from "./avatars";

export const initialElders = [
  {
    id: "elder-1",
    organizationId: "org_demo",
    status: "active",
    archivedAt: "",
    archivedReason: "",
    name: "王秀兰",
    age: 78,
    gender: "女",
    nickname: "秀兰阿姨",
    birthday: "1948-05-12",
    avatar: getChineseElderAvatar("elder-1", "女"),
    formerJob: "供销社营业员",
    lifeExperience: "年轻时在供销社站柜台，熟悉街坊邻里，喜欢讲以前工作中的人和事。",
    interests: "种花、听黄梅戏、晒太阳、整理旧照片",
    favoriteTopics: "年轻时工作经历、孙女上学、阳台花草",
    avoidTopics: "身体衰退、邻里纠纷、反复追问记忆细节",
    communicationStyle: "语速慢一点，多听她讲，先从花草和家人近况切入。",
    familyNote: "女儿每周三会来探望，希望服务人员顺手记录近况。",
    careNoteInput: "午后容易疲惫，建议上午探访；膝盖不太好，外出步行别太久。",
    staffNote: "聊到孙女和花草时明显更放松，适合用照片打开话题。",
    summary: "王秀兰有供销社营业员经历，适合从阳台花草聊起，陪伴时温和慢聊、多倾听。",
    tags: ["爱花草", "愿意聊天", "适合回忆陪伴", "AI整理"],
    aiFavoriteTopics: "阳台花草、年轻时工作经历、孙女近况、旧照片回忆",
    communicationAdvice: "语速慢一点，多听她讲，先从花草和家人近况切入；一次只问一个问题。",
    careNote: "建议上午探访，避免午后疲惫；外出步行时间不宜太久，可用花草和旧照片做轻量陪伴。",
    nextSuggestion: {
      opening: "下次可先从阳台花草温和聊起，例如“最近花开得怎么样？”",
      pace: "语速慢一点，先听她讲完，一次只问一个问题。",
      avoid: "不主动提身体衰退和邻里纠纷，如老人主动提到，先倾听和安抚。",
      followUp: "建议上午探访，可记录是否需要向女儿反馈精神状态和花草近况。",
    },
    updatedAt: "2026-05-03T08:30:00.000Z",
  },
  {
    id: "elder-2",
    organizationId: "org_demo",
    status: "active",
    archivedAt: "",
    archivedReason: "",
    name: "赵建国",
    age: 82,
    gender: "男",
    nickname: "建国叔",
    birthday: "",
    avatar: getChineseElderAvatar("elder-2", "男"),
    formerJob: "机械厂车工",
    lifeExperience: "在机械厂工作多年，做事讲究节奏和手艺，喜欢被认真倾听。",
    interests: "看老电影、下象棋、收听新闻",
    favoriteTopics: "厂里的老同事、国产老电影、象棋残局",
    avoidTopics: "经济压力、被催促锻炼、过多同情式安慰",
    communicationStyle: "先问近况再聊老电影，尊重他的节奏，不要频繁打断。",
    familyNote: "儿子在外地，平时电话联系较多，希望有人帮他记录想转达的话。",
    careNoteInput: "听力一般，面对面说话更清楚；情绪低落时不爱主动开口。",
    staffNote: "聊老电影时会更愿意开口，适合短时间探访。",
    summary: "赵建国曾是机械厂车工，喜欢有人耐心听他讲技术活，也愿意聊老电影。",
    tags: ["老电影", "听力一般", "尊重节奏", "AI整理"],
    aiFavoriteTopics: "国产老电影、厂里老同事、象棋残局、年轻时技术活",
    communicationAdvice: "先问近况再聊老电影，面对面说话更清楚，尊重他的节奏。",
    careNote: "面对面沟通更清楚；情绪低落时先短聊，不催促表达，可记录想转达给儿子的话。",
    nextSuggestion: {
      opening: "下次可带一段老电影片段做开场，再顺着电影人物聊到年轻时的工作。",
      pace: "面对面沟通，语速放慢，给他保留表达节奏，不频繁打断。",
      avoid: "不主动提经济压力，也不要用催促式语言劝锻炼。",
      followUp: "如聊到想对儿子说的话，可帮他整理成简短留言。",
    },
    updatedAt: "2026-05-02T14:10:00.000Z",
  },
  {
    id: "elder-3",
    organizationId: "org_demo",
    status: "active",
    archivedAt: "",
    archivedReason: "",
    name: "陈桂芳",
    age: 75,
    gender: "女",
    nickname: "桂芳奶奶",
    birthday: "1951-06-18",
    avatar: getChineseElderAvatar("elder-3", "女"),
    formerJob: "小学后勤",
    lifeExperience: "以前在小学后勤工作，熟悉孩子和校园生活，喜欢把小事做得细致。",
    interests: "编织、做手工、小点心、听戏曲",
    favoriteTopics: "手工作品、社区活动、家常点心做法",
    avoidTopics: "住院经历、拿她和同龄人比较",
    communicationStyle: "一起动手比单纯聊天更自然，鼓励式提问会更有回应。",
    familyNote: "外孙周末常来，喜欢看她做手工的视频。",
    careNoteInput: "手指关节有些僵硬，准备材料时尽量简单、轻便。",
    staffNote: "她愿意教别人做手工，被邀请示范时很有成就感。",
    summary: "陈桂芳爱做手工，喜欢有人一起做点小东西，不喜欢太正式的问答。",
    tags: ["手工陪伴", "温和稳定", "适合活动", "AI整理"],
    aiFavoriteTopics: "手工作品、家常点心做法、社区活动、外孙近况",
    communicationAdvice: "先一起做简单手工，再自然聊天；多用鼓励式提问，不做比较。",
    careNote: "手工材料要简单轻便，避免增加手指负担；边做边聊比连续问答更自然。",
    nextSuggestion: {
      opening: "下次可准备简单手工材料，请她先看看想从哪一步开始。",
      pace: "边做边聊，比连续提问更自然；回应时多肯定她的经验。",
      avoid: "不主动提住院经历，也不拿她和其他同龄人比较。",
      followUp: "可记录她愿意教别人的手工步骤，后续邀请参加小型手工活动。",
    },
    updatedAt: "2026-05-01T10:15:00.000Z",
  },
];

export const initialOpportunities = [
  {
    id: "op-demo-ai-1",
    organizationId: "org_demo",
    elderId: "elder-1",
    type: "重点关注",
    title: "建议安排一次温和回访",
    description: "张奶奶最近服务记录中多次提到“睡眠不好、情绪低落”，建议本周安排一次温和回访，可从戏曲和花草话题切入。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-04",
    createdAt: "2026-05-01T08:00:00.000Z",
    source: "ai",
    isDemo: true,
  },
  {
    id: "op-demo-ai-2",
    organizationId: "org_demo",
    elderId: "elder-3",
    type: "重点关注",
    title: "建议补充一次近况了解",
    description: "李阿姨喜欢聊家庭照片和节日饭菜，建议联系家属补充一张老照片，并记录照片背后的故事。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-06",
    createdAt: "2026-05-01T08:10:00.000Z",
    source: "ai",
  },
  {
    id: "op-demo-ai-3",
    organizationId: "org_demo",
    elderId: "elder-2",
    type: "重点关注",
    title: "建议安排一次短时问候",
    description: "建国叔最近两次记录都提到情绪偏低，建议先做一次 10 分钟左右的电话问候，再决定是否安排现场探访。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-13",
    createdAt: "2026-05-01T08:24:00.000Z",
    source: "ai",
  },
  {
    id: "op-demo-ai-4",
    organizationId: "org_demo",
    elderId: "elder-3",
    type: "活动邀请",
    title: "建议安排一次轻活动陪伴",
    description: "桂芳奶奶在手工活动中更愿意主动交流，建议下次继续以简单手工作为切入，观察她近期精神状态。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-14",
    createdAt: "2026-05-01T08:25:00.000Z",
    source: "ai",
  },
  {
    id: "op-demo-ai-5",
    organizationId: "org_demo",
    elderId: "elder-1",
    type: "电话问候",
    title: "建议同步一次睡眠近况",
    description: "张奶奶最近多次提到夜里睡得不稳，建议在下次服务后同步家属，确认是否需要进一步关注作息变化。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-15",
    createdAt: "2026-05-01T08:26:00.000Z",
    source: "ai",
  },
  {
    id: "op-demo-rule-1",
    organizationId: "org_demo",
    elderId: "elder-2",
    type: "长期未探访",
    title: "超过 7 天未形成服务记录",
    description: "王叔叔已有一段时间没有新的服务记录，建议安排一次电话问候或现场探访。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-07",
    createdAt: "2026-05-01T08:15:00.000Z",
    source: "rule",
  },
  {
    id: "op-demo-rule-2",
    organizationId: "org_demo",
    elderId: "elder-3",
    type: "生日关怀",
    title: "生日关怀提醒",
    description: "李阿姨的关怀日期临近，建议提前准备一句祝福，或邀请家属录制语音问候。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-08",
    createdAt: "2026-05-01T08:18:00.000Z",
    source: "rule",
  },
  {
    id: "op-demo-rule-3",
    organizationId: "org_demo",
    elderId: "elder-1",
    type: "画像待完善",
    title: "知老卡信息待完善",
    description: "张奶奶的知老卡中“需要避开的话题”和“家属提醒”信息较少，建议下次服务后补充完善。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-09",
    createdAt: "2026-05-01T08:19:00.000Z",
    source: "rule",
  },
  {
    id: "op-demo-rule-4",
    organizationId: "org_demo",
    elderId: "elder-2",
    type: "电话问候",
    title: "本周应补一次近况回访",
    description: "根据固定规则，建国叔本周尚未形成新的关怀记录，建议至少完成一次电话回访。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-13",
    createdAt: "2026-05-01T08:27:00.000Z",
    source: "rule",
  },
  {
    id: "op-demo-rule-5",
    organizationId: "org_demo",
    elderId: "elder-3",
    type: "画像待完善",
    title: "补充家属提醒信息",
    description: "系统发现桂芳奶奶的家属提醒字段较少，建议下次服务后补充外孙探访频率与互动偏好。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-14",
    createdAt: "2026-05-01T08:28:00.000Z",
    source: "rule",
  },
  {
    id: "op-demo-manual-1",
    organizationId: "org_demo",
    elderId: "elder-2",
    type: "探访安排",
    title: "本周五安排一次入户探访",
    description: "工作人员手动创建：本周五下午安排志愿者上门探访，重点了解近期生活状态。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-10",
    createdAt: "2026-05-01T08:21:00.000Z",
    source: "manual",
    createdByName: "王老师",
    createdByRole: "staff",
  },
  {
    id: "op-demo-manual-2",
    organizationId: "org_demo",
    elderId: "elder-1",
    type: "电话问候",
    title: "联系家属补充近况",
    description: "工作人员手动创建：请联系家属了解张奶奶最近饮食、睡眠和情绪情况。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-11",
    createdAt: "2026-05-01T08:22:00.000Z",
    source: "manual",
    createdByName: "刘社工",
    createdByRole: "staff",
  },
  {
    id: "op-demo-manual-3",
    organizationId: "org_demo",
    elderId: "elder-3",
    type: "活动邀请",
    title: "邀请参加周末茶话会",
    description: "工作人员手动创建：李阿姨喜欢做饭和聊天，可邀请参加周末社区茶话会。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-12",
    createdAt: "2026-05-01T08:23:00.000Z",
    source: "manual",
    createdByName: "机构管理员",
    createdByRole: "org_admin",
  },
  {
    id: "op-demo-manual-4",
    organizationId: "org_demo",
    elderId: "elder-1",
    type: "电话问候",
    title: "周三上午安排一次电话关怀",
    description: "工作人员手动创建：周三上午由值班工作人员电话问候张奶奶，重点了解本周睡眠和精神状态。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-13",
    createdAt: "2026-05-01T08:29:00.000Z",
    source: "manual",
    createdByName: "王老师",
    createdByRole: "staff",
  },
  {
    id: "op-demo-manual-5",
    organizationId: "org_demo",
    elderId: "elder-2",
    type: "电话问候",
    title: "联系儿子确认近期来访安排",
    description: "工作人员手动创建：请与建国叔儿子确认本月是否有来访计划，便于同步后续关怀安排。",
    status: "pending",
    relatedRecordId: "",
    completedAt: "",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-14",
    createdAt: "2026-05-01T08:30:00.000Z",
    source: "manual",
    createdByName: "刘社工",
    createdByRole: "staff",
  },
  {
    id: "op-4",
    organizationId: "org_demo",
    elderId: "elder-1",
    type: "家属留言建议",
    title: "家属希望补充近况反馈",
    description: "下次探访时可记录一次自然状态，并向家属反馈老人精神状态。",
    status: "completed",
    relatedRecordId: "rec-1",
    completedAt: "2026-05-02T09:20:00.000Z",
    dismissReason: "",
    dismissedAt: "",
    dueDate: "2026-05-02",
    createdAt: "2026-05-01T08:20:00.000Z",
    source: "rule",
  },
];

export const initialRecords = [
  {
    id: "rec-1",
    organizationId: "org_demo",
    elderId: "elder-1",
    relatedOpportunityId: "op-4",
    generatedOpportunities: [],
    serviceType: "探访",
    durationHours: 1.5,
    durationStatus: "confirmed",
    elderStatus: "开心",
    content: "一起看了阳台上的花，聊了她年轻时在供销社站柜台的事，情绪很好。",
    newInfo: "最近最惦记的是孙女考试，提到玫瑰花开了很开心。",
    nextSuggestion: {
      opening: "下次可继续从花草和孙女近况聊起。",
      pace: "让她先讲，服务人员只做轻声回应和少量追问。",
      avoid: "不主动提身体衰退和邻里纠纷。",
      followUp: "可一起整理旧照片，并记录是否需要给女儿反馈。",
    },
    createdAt: "2026-05-02T09:20:00.000Z",
    operatorName: "李晨",
  },
  {
    id: "rec-2",
    organizationId: "org_demo",
    elderId: "elder-2",
    relatedOpportunityId: "",
    generatedOpportunities: [],
    serviceType: "康复回访",
    durationHours: 1,
    durationStatus: "confirmed",
    elderStatus: "低落",
    content: "通话时间不长，提到最近看了一部老电影，愿意简单聊两句。",
    newInfo: "对《地道战》这类老片依然很有兴趣。",
    nextSuggestion: {
      opening: "下次可带老电影片段探访，先从电影情节聊起。",
      pace: "面对面慢慢说，不催他表达。",
      avoid: "不主动提经济压力，也不要用同情式安慰。",
      followUp: "优先安排一次短探访，观察低落状态是否持续。",
    },
    createdAt: "2026-05-01T16:45:00.000Z",
    operatorName: "周岚",
  },
  {
    id: "rec-3",
    organizationId: "org_demo",
    elderId: "elder-3",
    relatedOpportunityId: "",
    generatedOpportunities: [],
    serviceType: "活动",
    durationHours: 2,
    durationStatus: "confirmed",
    elderStatus: "平稳",
    content: "陪她做了简单的纸花手工，她很愿意教别人怎么折。",
    newInfo: "她对带别人一起做手工很有成就感。",
    nextSuggestion: {
      opening: "下次可准备简单编织材料，请她先示范一步。",
      pace: "边做边聊，多肯定她的经验。",
      avoid: "不拿她和别人比较。",
      followUp: "适合邀请参加小型手工活动，让她带别人一起做。",
    },
    createdAt: "2026-04-30T14:00:00.000Z",
    operatorName: "王娟",
  },
];

export const initialNewsPosts = [
  {
    id: "news-platform-1",
    organizationId: "",
    scope: "platform",
    title: "知老平台试点动态",
    summary: "知老继续完善长者档案、服务提醒和隐私保护能力。",
    content: "知老平台正在试点轻量化长者服务协作工具，帮助机构沉淀长者画像、服务记录和后续关怀提醒。动态内容涉及长者信息时，请注意保护隐私。",
    category: "系统",
    status: "published",
    coverImageUrl: "",
    authorId: "",
    authorName: "知老平台",
    publishedAt: "2026-05-08T09:00:00.000Z",
    createdAt: "2026-05-08T09:00:00.000Z",
    updatedAt: "2026-05-08T09:00:00.000Z",
  },
  {
    id: "news-org-1",
    organizationId: "org_demo",
    scope: "organization",
    title: "本周电话问候安排",
    summary: "本周优先关注长期未探访和近期情绪低落的长者。",
    content: "请服务人员结合服务机会列表，优先完成本周电话问候和短探访。记录内容请尽量脱敏，避免填写完整电话、详细住址和身份证号。",
    category: "通知",
    status: "published",
    coverImageUrl: "",
    authorId: "user_demo_admin",
    authorName: "张晓明",
    publishedAt: "2026-05-07T10:30:00.000Z",
    createdAt: "2026-05-07T10:30:00.000Z",
    updatedAt: "2026-05-07T10:30:00.000Z",
  },
];
